source:
  #univ_url: "http://fund.jrj.com.cn/family.shtml"
  univ_url: "http://fund.eastmoney.com/js/fundcode_search.js"
  fund_home_url: "http://fund.eastmoney.com/{index}.html?spm=search"
  hist_url: "http://fund.eastmoney.com/f10/jjjz_{index}.html"

output:
  fund_univ: data/fund_univ.csv
  hist_prc: data/{index}.csv

logging:
  version: 1
  root:
    level: INFO
    handlers: [console, logfile]
  formatters:
    simple:
      format: '%(asctime)s %(levelname)s--: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
    logfile:
      class: logging.FileHandler
      level: INFO
      filename: main.log
      formatter: simple
      mode: "w"